name: build-and-push-by-label
on:
  issues:
    types:
      - "labeled"
  push:
    branches:
      - "master"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: download
        if: ${{ github.event.label.name }} == 'bug'
        uses: bit-orbit/issue-2-hugo-post@master
        with:
          NAME: 'carbon'
          OWNER: 'shabane'
          PUB_DIR: 'content'
          DEBUG: True